steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/colorful-learningcards/cloud-run-test:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/colorful-learningcards/cloud-run-test:$SHORT_SHA', '.']
